export const demoData = {
  item: {
    appId: 730,
    marketName: "MP9 | Wild Lily (Factory New)",
    price: 529482,
    details: {
      colors: ["Purple", "Blue"],
      description:
        "Submachine gun. Based on the Brugger & Thomet APC9 submachine gun developed in Switzerland in 2010. Among the main advantages of MP9 are high accuracy, low price, and high kill award. Disadvantages include high recoil, low spread, low armor penetration, and low damage. A custom paint job of a blue lily has been hand painted over a purple base.\n\n<i>Stop and smell the cordite</i>",
      floatMin: 0,
      floatMax: 70,
      weapon: "MP9",
      skin: "Wild Lily",
      variantName: "MP9 | Wild Lily",
      exterior: "FACTORY_NEW",
      rarity: "CLASSIFIED",
      type: "SMG",
      statTrak: false,
      souvenir: false,
      releasedAt: "2019-11-18T00:00:00.000Z",
    },
    definitionId: null,
    imageUrl:
      "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou6r8FAR17P7YKAJL_9C3moS0kfv7IbrdqWdY781lxLuX99nz2AW1r0o-YmqlLdXHcQJsZF7X8we4wuvqhMW8tJTPy3djunQ8pSGKEli0QAg",
    hasDescription: true,
  },
  status: "NONE",
  appId: 730,
  assetId: "44554906936",
  amount: 1,
  tradableAfter: "2025-06-21T07:00:00.000Z",
  game730: {
    assetId: "44554906936",
    paintWear: 0.04388608410954,
    paintIndex: 734,
    paintSeed: 33,
    fadePercent: null,
    pattern: null,
    bluePercent: null,
    nameTag: null,
    isScreenshotSupported: true,
    hasPaint: true,
    inspectUrl:
      "steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561199654235498A44554906936D12278572817000884976",
    screenshotUrl:
      "https://cdn.skinsmonkey.com/assets/44554906936?v1749835179888",
    keychains: [],
    stickers: [
      {
        index: 0,
        type: "STICKER",
        wear: "1",
        slot: 0,
        rotation: 174,
        offsetX: "-0.05004054307937622",
        offsetY: "0.001747816801071167",
        offsetZ: null,
        pattern: null,
        inspected: true,
        marketName: "Sticker | Miami Flick (Holo)",
        imageUrl:
          "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRVzETuCo6NzGQVtnLQtH-bypIgRr7KOcP2gQvd7iwtaOk67xZeiGkzsHuJUm3bzHpt-iiQSxr0ZsazzxcYbHcwYgIQaHS1p6SAI",
        price: 1189,
      },
      {
        index: 1,
        type: "STICKER",
        wear: "1",
        slot: 2,
        rotation: -123,
        offsetX: "0.24008288979530334",
        offsetY: "0.03153085708618164",
        offsetZ: null,
        pattern: null,
        inspected: true,
        marketName: "Sticker | Miami Flick (Holo)",
        imageUrl:
          "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRVzETuCo6NzGQVtnLQtH-bypIgRr7KOcP2gQvd7iwtaOk67xZeiGkzsHuJUm3bzHpt-iiQSxr0ZsazzxcYbHcwYgIQaHS1p6SAI",
        price: 1189,
      },
      {
        index: 2,
        type: "STICKER",
        wear: "1",
        slot: 2,
        rotation: -42,
        offsetX: "0.29526638984680176",
        offsetY: "0.012545198202133179",
        offsetZ: null,
        pattern: null,
        inspected: true,
        marketName: "Sticker | Miami Flick (Holo)",
        imageUrl:
          "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRVzETuCo6NzGQVtnLQtH-bypIgRr7KOcP2gQvd7iwtaOk67xZeiGkzsHuJUm3bzHpt-iiQSxr0ZsazzxcYbHcwYgIQaHS1p6SAI",
        price: 1189,
      },
      {
        index: 3,
        type: "STICKER",
        wear: "1",
        slot: 2,
        rotation: 9,
        offsetX: "0.2934347093105316",
        offsetY: "-0.02360159158706665",
        offsetZ: null,
        pattern: null,
        inspected: true,
        marketName: "Sticker | Miami Flick (Holo)",
        imageUrl:
          "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRVzETuCo6NzGQVtnLQtH-bypIgRr7KOcP2gQvd7iwtaOk67xZeiGkzsHuJUm3bzHpt-iiQSxr0ZsazzxcYbHcwYgIQaHS1p6SAI",
        price: 1189,
      },
      {
        index: 4,
        type: "STICKER",
        wear: "1",
        slot: 4,
        rotation: 78,
        offsetX: "0.08388912677764893",
        offsetY: "-0.19593867659568787",
        offsetZ: null,
        pattern: null,
        inspected: true,
        marketName: "Sticker | Miami Flick (Holo)",
        imageUrl:
          "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPRVzETuCo6NzGQVtnLQtH-bypIgRr7KOcP2gQvd7iwtaOk67xZeiGkzsHuJUm3bzHpt-iiQSxr0ZsazzxcYbHcwYgIQaHS1p6SAI",
        price: 1189,
      },
    ],
  },
  overstock: {
    limit: 1,
    available: 0,
    stock: 1,
  },
  imageUrl:
    "https://cdn.skinsmonkey.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou6r8FAR17P7YKAJL_9C3moS0kfv7IbrdqWdY781lxLuX99nz2AW1r0o-YmqlLdXHcQJsZF7X8we4wuvqhMW8tJTPy3djunQ8pSGKEli0QAg",
  uniqueId: "730:44554906936",
  stackable: false,
  stackId: 18177,
  tradeLockTime: 172779,
  tradeLock: true,
  notAccepted: false,
  type: "SITE",
  virtual: false,
};

export const phase = [
  "Black Pearl",
  "Emerald",
  "Phase 1",
  "Phase 2",
  "Phase 3",
  "Phase 4",
  "Ruby",
  "Sapphire",
];

export const rarity = [
  { text: "Consumer Grade", color: "text-gray-300" },
  { text: "Industrial Grade", color: "text-blue-400" },
  { text: "Mil-Spec Grade", color: "text-blue-500" },
  { text: "Restricted", color: "text-purple-400" },
  { text: "Classified", color: "text-pink-400" },
  { text: "Covert", color: "text-red-500" },
  { text: "Contraband", color: "text-yellow-400" },
];

export const collections = [
  "Limited Edition Item",
  "Operation Hydra",
  "2018 Inferno",
  "2018 Nuke",
  "2021 Dust 2",
  "2021 Mirage",
  "2021 Train",
  "2021 Vertigo",
  "Alpha",
  "Ancient",
  "Anubis",
  "Arms Deal",
  "Arms Deal 2",
  "Arms Deal 3",
  "Assault",
  "Aztec",
  "Baggage",
  "Bank",
  "Blacksite",
  "Boreal",
  "Bravo",
  "Breakout",
  "Cache",
  "Canals",
  "Chop Shop",
  "Chroma",
  "Chroma 2",
  "Chroma 3",
  "Clutch",
  "Cobblestone",
  "Control",
  "CS20",
  "Danger Zone",
  "Dreams & Nightmares",
  "Dust",
  "Dust 2",
  "ESports 2013",
  "ESports 2013 Winter",
  "ESports 2014 Summer",
  "Esports Winter",
  "Falchion",
  "Fever",
  "Fracture",
  "Gallery",
  "Gamma",
  "Gamma 2",
  "Glove",
  "Gods And Monsters",
  "Graphic Design",
  "Havoc",
  "Horizon",
  "Huntsman",
  "Inferno",
  "Italy",
  "Kilowatt",
  "Lake",
  "Militia",
  "Mirage",
  "Norse",
  "Nuke",
  "Office",
  "Operation Broken Fang",
  "Operation Riptide",
  "Overpass",
  "Overpass 2024",
  "Phoenix",
  "Prisma",
  "Prisma 2",
  "Radiant",
  "Recoil",
  "Revolution",
  "Revolver Case",
  "Rising Sun",
  "Safehouse",
  "Shadow",
  "Shattered Web",
  "Snakebite",
  "Spectrum",
  "Spectrum 2",
  "Sport & Field",
  "St. Marc",
  "Train",
  "Train 2025",
  "Vanguard",
  "Vertigo",
  "Wildfire",
  "Winter Offensive",
  "X Ray",
];
